apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.20-alpine
        name: nginx
        resources: {}
        livenessProbe:
          initialDelaySeconds: 5
          failureThreshold: 5
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        readinessProbe:
          initialDelaySeconds: 2
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
status: {}
