apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: http-echo
  name: http-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: http-echo
    spec:
      containers:
      - image: hashicorp/http-echo:0.2.0
        name: http-echo
        command:
        - /http-echo
        args:
        - -listen=:8090
        - -text="Hello World v1.0!"
        resources: {}
