apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: http-echo
  name: http-echo
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: http-echo