apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: htto-echo
  name: htto-echo
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: htto-echo