apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: buildpacks-test-pipeline-run
spec:
  serviceAccountName: buildpacks-service-account
  pipelineRef:
    name: buildpacks-test-pipeline
  params:
    - name: gitUrl
      value: https://github.com/kurtburak/k8s-demo
    - name: appSourcePath
      value: 'apps/java-maven'
    - name: appBuilderImage
      value: 'paketobuildpacks/builder:base'
    - name: deployImage
      value: docker.io/bkurt/demoapp:latest
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: buildpacks-source-pvc
  resources:
  - name: build-image
    resourceRef:
      name: buildpacks-app-image
  podTemplate:
    volumes:
    - name: buildpacks-cache
      persistentVolumeClaim:
        claimName: buildpacks-cache-pvc
